#############################################################################
# 									    #
# Makefile to compile and link FORTRAN programs                             #
#  									    #
# "make" compiles and links the specified main programs and modules,        #
# using the specified libraries (if any), and produces the executables      #
#									    #
# "make clean" removes all files generated by "make"                        #
#                                                                           #
#############################################################################

all: rmxeq mkxeq
.PHONY: all

# main programs to be compiled 
MAIN = test

# List of the modules to include
MODULES = subgrid grid evolsetup evolinit distset opset splittings utils

# Path with all the directories where modules should be searched by the Makefile
VPATH = src

############################## do not change #############################

SHELL=/bin/bash

CC=g++

CFLAGS = -O3 -Wunused -std=c++11 -I./inc 

CLINKER=$(CC)

PGMS= $(MAIN) $(MODULES)

-include $(addsuffix .d,$(PGMS))

# rule to compile source programs
$(addsuffix .o,$(PGMS)): %.o: %.cc Makefile
	$(CC) $< -c $(CFLAGS) 

# rule to link object files
$(MAIN): %: %.o $(addsuffix .o,$(MODULES)) Makefile
	@ $(CLINKER) $< $(addsuffix .o,$(MODULES)) $(CFLAGS) -o $@

# produce executables
mkxeq: $(MAIN)

# remove old executables
rmxeq:
	@ -rm -f $(MAIN); \
        echo "delete old executables"		

# clean directory
clean:
	@ -rm -rf *.o *~ $(MAIN)
.PHONY: clean

############################################################################
